// <auto-generated />
using System;
using Epic_Booking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Epic_Booking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Epic_Booking.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 123,
                            End = new DateTime(2023, 6, 1, 15, 59, 22, 307, DateTimeKind.Local).AddTicks(3680),
                            Start = new DateTime(2023, 6, 1, 13, 59, 22, 307, DateTimeKind.Local).AddTicks(3300),
                            Title = "Booking 1"
                        },
                        new
                        {
                            Id = 456,
                            End = new DateTime(2023, 6, 2, 15, 59, 22, 307, DateTimeKind.Local).AddTicks(3780),
                            Start = new DateTime(2023, 6, 2, 13, 59, 22, 307, DateTimeKind.Local).AddTicks(3770),
                            Title = "Booking 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
